#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

require __DIR__.'/bootstrap/app.php';

$status = (int) $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

exit($status);
